name : Postman Collection Workflow
name: Postman Collection Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
   -cron: '30 02 * * *'  #8 am IST evenryday
   -cron : '00 14 * * *' # 7:30 pm IST everyday
   

   jobs:
     run-postman-tests:
       runs-on: ubuntu-latest

    steps:
      -name : checkout the code
       uses: actions/checkout@v6.0.2
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '22'

          -name : Install newman htmlextra globally
          run:  | 
              npm install -g newman
              npm install -g newman-reporter-htmlextra

              -name : run the postman collection with newman
                run : |  
                newman run 'Inwarranty-flow Collection.postman_collection.json' \
                -e QA.postman_environment.json \
                -d testData.csv \
                -r cli,htmlextra
                
                
                
       
      
       
  
